### ISSUE TITLE
Possibly picking up incorrect colors

### ISSUE THREAD

**Issue by onlineth** [Zottelchen/jca#1]
It does not seem to be picking up the correct colors when using a two color image, below is a screenshot of what I'm seeing,

![Screenshot of Issue](https://i.imgur.com/qtulYNl.png)

**Comment by Zottelchen** [comment]
Will fix it later today/tomorrow. Probably has something to do with Java shitty getRGB.
see:
http://stackoverflow.com/questions/13072312/jpeg-image-color-gets-drastically-changed-after-just-imageio-read-and-imageio
http://stackoverflow.com/questions/9340569/jpeg-image-with-wrong-colors
http://stackoverflow.com/questions/32804784/weird-rgb-value-from-java-bufferedimage-getrgb

**Comment by Zottelchen** [comment]
539125e7e059a2fbfbdda7db7793b4d4de674a1a

Maybe that did it? Let's try this.

**Comment by onlineth** [comment]
Did the trick?

**Comment by onlineth** [comment]
Sweet, it works:D
